### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by EinsKatze**
- Fix a crash
- Fix logging messages that show no change (Discord adding the Embed to a Message with a Link)
- Change 'user.tag' -> 'user.username' (Discord does not use tags/discriminators anymore)
- Some formatting changes (from prettier)
- Always use tsc when starting the bot to ensure all commands get registered when using 'npm run dev'

### CODE REVIEW

**Review by filip326 — CHANGES_REQUESTED** [review]
Replace npm run start with tsc && node . please.

Abd use yarn

**Comment by Barsch2006** [comment]
> Replace npm run start with tsc && node . please.
> 
> Abd use yarn

Still requesting a poll for that one

**Comment by EinsKatze** [comment]
> Replace npm run start with tsc && node . please.
> 
> Abd use yarn

[Line 29 in package.json](https://github.com/EinsKatze/FloBot/blob/c992ab3e2dcc022cd7c316cac62745e0d39cb66b/package.json#L29) - it already is `tsc && node .`.

Yarn isn't mentioned anywhere in the Repository, so how would one know that we should use yarn?
And tbh i don't get why one would even use yarn when npm gets installed when installing NodeJS.

**Review by Mickhat — APPROVED** [review]

**Comment by filip326** [comment]
> > Replace npm run start with tsc && node . please.
> > 
> > Abd use yarn
> 
> [Line 29 in package.json](https://github.com/EinsKatze/FloBot/blob/c992ab3e2dcc022cd7c316cac62745e0d39cb66b/package.json#L29) - it already is `tsc && node .`.
> 
> Yarn isn't mentioned anywhere in the Repository, so how would one know that we should use yarn?
> And tbh i don't get why one would even use yarn when npm gets installed when installing NodeJS.

I'm telling you right now and Mickhat told me earlier

**Comment by EinsKatze** [comment]
> > > Replace npm run start with tsc && node . please.
> > > Abd use yarn
> > 
> > 
> > [Line 29 in package.json](https://github.com/EinsKatze/FloBot/blob/c992ab3e2dcc022cd7c316cac62745e0d39cb66b/package.json#L29) - it already is `tsc && node .`.
> > Yarn isn't mentioned anywhere in the Repository, so how would one know that we should use yarn?
> > And tbh i don't get why one would even use yarn when npm gets installed when installing NodeJS.
> 
> I'm telling you right now and Mickhat told me earlier

As of now everything in the Repo indicates that we are using npm.
"Im telling you right now" is not a good way to handle such things in an open source repository. If you're willing to structure the Repository in a way were it's clear that i should use yarn, i might do.
Nonetheless it's not really relevant for this PR.
Please approve the changes - you requested changes which cannot be done.

**Pull request merged**
