### PR TITLE
npm upgrade

### PR DESCRIPTION
**Pull request by chfuchte**
@typescript-eslint/no-misused-promises offed as well as it don't allowes async arrow functions as args for discord.js event handler

### CODE REVIEW

**Comment by chfuchte** [comment]
seems like we cantseams like discord.js can not be updated with our tsconfig

**Comment by EinsKatze** [comment]
Running `npm audit fix --force` seems to work (at least in my case), to upgrade some things.
Might be worth to do that first, then figure out how to upgrade further.

**Comment by EinsKatze** [comment]
Also, in the discord.js repo there is a issue for this. https://github.com/discordjs/discord.js/issues/9783
Using Typescript V5 seems to be the fix.

**Comment by EinsKatze** [comment]
> Also, in the discord.js repo there is a issue for this. [discordjs/discord.js#9783](https://github.com/discordjs/discord.js/issues/9783) Using Typescript V5 seems to be the fix.

Seems to work (for me), but a few files are using functions which seem to work different in discord.js now.

`interaction.options.getMember()` and `interaction.options.getUser()` does not exist anymore and is used in:
```
src/action/blackjack/registerCommands.ts:24
src/commands/clear.ts:4
src/commands/history.ts:2
src/commands/rename.ts:25
src/commands/strike.ts:29
src/commands/ticket-add.ts:2
src/commands/warn.ts:30
```

**Comment by EinsKatze** [comment]
> > Also, in the discord.js repo there is a issue for this. [discordjs/discord.js#9783](https://github.com/discordjs/discord.js/issues/9783) Using Typescript V5 seems to be the fix.
> 
> Seems to work (for me), but a few files are using functions which seem to work different in discord.js now.
> 
> `interaction.options.getMember()` and `interaction.options.getUser()` does not exist anymore ([docs say otherwise tho](https://discord.js.org/docs/packages/discord.js/main/CommandInteractionOptionResolver:Class)) and is used in:
> 
> ```
> src/action/blackjack/registerCommands.ts:24
> src/commands/clear.ts:4
> src/commands/history.ts:2
> src/commands/rename.ts:25
> src/commands/strike.ts:29
> src/commands/ticket-add.ts:2
> src/commands/warn.ts:30
> ```

We need to Switch the line `async execute(interaction: CommandInteraction)` to `async execute(interaction: ChatInputCommandInteraction)`.

There is a different error in src/action/blackjack/registerCommands.ts:24 tho, which is different from the interaction options mentioned above.

**Comment by EinsKatze** [comment]
Have don't most of the changes mentioned. (https://github.com/EinsKatze/FloBot/commit/f863640c6c8363071f0094dc272875524f239f78)

Don't know how to fix blackjack issue rn

**Comment by chfuchte** [comment]
Thanks for the research @EinsKatze

**Comment by EinsKatze** [comment]
I fixed the Blackjack issue now [in my fork](https://github.com/EinsKatze/FloBot) aswell but had to deactivate a eslint rule.
The Rule seems to do weird things with promises in the new TS version idk.

**Comment by chfuchte** [comment]
> I fixed the Blackjack issue now [in my fork](https://github.com/EinsKatze/FloBot) aswell but had to deactivate a eslint rule. The Rule seems to do weird things with promises in the new TS version idk.

yes, I had to disable it as well (see first commit here)

**Pull request closed without merging**
